"""add simulation column to plans

Revision ID: 0bd532401958
Revises: 81efa353a255
Create Date: 2026-01-20 16:20:57.280743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd532401958'
down_revision: Union[str, None] = '81efa353a255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('simulation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'simulation')
    # ### end Alembic commands ###
